[package]
name = "db"
version = "0.1.0"
authors = ["jude"]
edition = "2018"

[dependencies]
serde_json = "1.0.47"

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dependencies.diesel]
version = "1.4.3"
features = ["serde_json", "postgres", "r2d2"]
